# Generated by Django 3.2.6 on 2021-09-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210919_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date_created',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='description',
            new_name='memo',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='importent',
        ),
        migrations.AddField(
            model_name='todo',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
